name = "Flywheel New Continent"
author = "CreepSean"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0ce86eea625630c388729f6816fe4033e9f45dd7ec961c922ea45d3bde33b0f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.146"
