name = "Flywheel New Continent"
author = "CreepSean"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e176a2816fd493f9710eb06277087ea223d740392320f095eb906b19c8a0a9d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.146"
